# (Wallust removido) los colores de borde se definen fijos en settings.conf

source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/autostart.conf
source = ~/.config/hypr/configs/environments.conf
source = ~/.config/hypr/configs/settings.conf
source = ~/.config/hypr/configs/rules.conf
source = ~/.config/hypr/configs/binds.conf
