# ╔════════════════════════════════════════════════╗
# ║        HYPRLAND MASTER CONFIGURATION           ║
# ╚════════════════════════════════════════════════╝
# Archivo modular. Carga las configuraciones por orden lógico.

# 1. Cargar colores dinámicos de Wallust
source = ~/.cache/wallust/colors-hyprland.conf

source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/autostart.conf
source = ~/.config/hypr/configs/environments.conf
source = ~/.config/hypr/configs/settings.conf
source = ~/.config/hypr/configs/rules.conf
source = ~/.config/hypr/configs/binds.conf
