[opener]
pdf = [
  { run = 'firefox "$@"', desc = "Firefox", orphan = true, for = "linux" },
]

# prepend_rules se evalúa antes del catch-all del default.
[open]
prepend_rules = [
  { mime = "application/pdf", use = [ "pdf", "open", "reveal" ] },
]
