exec-once = dbus-update-activation-environment --systemd --all
exec-once = systemctl --user import-environment DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP XDG_SESSION_DESKTOP

# UI
exec-once = waybar
exec-once = mako
exec-once = awww-daemon

# OSD
exec-once = swayosd-server

# Network tray
exec-once = nm-applet

# Screen lock / idle
exec-once = hypridle -c ~/.config/hypr/hypridle.conf

# Screen share compatibility (Discord / edge cases)
exec-once = xwaylandvideobridge

# Clipboard history (texto e imágenes)
exec-once = wl-paste --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
