env = XCURSOR_SIZE,24
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland

# Qt (Wayland con fallback xcb)
env = QT_QPA_PLATFORM,wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_AUTO_SCREEN_SCALE_FACTOR,0
env = QT_QPA_PLATFORMTHEME,qt6ct

# Electron / Chromium (Teams, Discord, Meet)
env = MOZ_ENABLE_WAYLAND,1
env = NIXOS_OZONE_WL,1
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
